### ISSUE TITLE
[Feat] 삭제에 따른 정책 점검

### ISSUE THREAD

**Issue by mobzzzzz** [one-day-one-meal/one-hour-one-meal#56]
*# 기능 설명
이번 프로젝트는 양방향 관계를 다루지 않기 때문에
Cascade를 통한 삭제를 진행하지 않으니 로직에서 고아객체가 생성되지 않게 주의해야 합니다.

# To-do
- [x] 전체적인 삭제의 전파 정책을 점검 (예: 강의가 삭제되면 레시피랑 댓글도 삭제해야하나?, 댓글이 삭제되면 신고 기록은 남길까 삭제할까?)
- [x] 로직에서 삭제 전파 구현
- [ ] #74

# ETC
강의같은 핵심 도메인과 다르게 작성자의 경우 연관관계의 주연이라기 보다는 그냥 작성자를 구분하는 느낌이 있는데
id를 nullable하게 뒀으니 Dto에 null을 그대로 보내고 프론트에서 처리할 때 (탈퇴한 유저입니다.) 등의 처리를 한다고 가정하면 괜찮을 것 같습니다.

**Comment by ckhcree** [comment]
피그마, erd, api 명세서 보고 전체 체크 하면 되겟지요?
